"""Bilingual SDE theory: English is canonical, Spanish is title_es / reading_es."""
from __future__ import annotations


# (week_id, title_en, title_es, anchor_en, anchor_es, [(title_en, title_es, reading_en, reading_es), ...])
WEEKS: list[tuple] = [
    ("w01-big-o", "Big O", "Big O", "Codenda", "Codenda", [
        ("O(1), O(n), O(n²)", "O(1), O(n), O(n²)",
         "O(1) does not grow with n. O(n) is one loop. O(n²) is a loop inside a loop. Brute Two Sum is O(n²); with a dict it is O(n).",
         "O(1) no crece con n. O(n) un loop. O(n²) loop dentro de loop. Two Sum brute es O(n²); con dict es O(n)."),
        ("O(log n) and O(n log n)", "O(log n) y O(n log n)",
         "O(log n) splits the search space (binary search). O(n log n) is sort. Do not recite the table: say what your code does.",
         "O(log n) parte el espacio (binary search). O(n log n) es sort. No recites la tabla: di qué hace tu código."),
        ("Time vs space", "Tiempo vs espacio",
         "Sometimes you pay memory (the Two Sum dict) to cut time. State both when you finish an LC.",
         "A veces pagas memoria (el dict de Two Sum) para bajar tiempo. Di ambos al acabar un LC."),
        ("How you say it", "Cómo lo dices",
         "Phrase: 'One pass, map value→index, O(n) time O(n) space.' Practice it out loud.",
         "Frase: 'Un pass, mapa valor→índice, O(n) tiempo O(n) espacio.' Practícala en voz alta."),
        ("Big O close", "Cierre Big O",
         "If you cannot say Two Sum complexity without reading, the section is not closed.",
         "Si no puedes decir la complejidad de Two Sum sin leer, la sección no está cerrada."),
    ]),
    ("w02-rest", "REST", "REST", "eLink", "eLink", [
        ("Status codes", "Status codes",
         "2xx ok, 4xx client, 5xx server. 200 with a SOAP Fault XML (eBay) is a broken contract: the code lies.",
         "2xx ok, 4xx cliente, 5xx servidor. 200 con Fault XML (eBay SOAP) es un contrato roto: el código miente."),
        ("Idempotency", "Idempotencia",
         "GET/PUT/DELETE can be retried. POST /orders cannot. eLink dual-run: one writer once the diff was 0.",
         "GET/PUT/DELETE se pueden retriar. POST /orders no. Dual-run eLink: un solo writer cuando el diff fue 0."),
        ("Pagination", "Paginación",
         "Offset is simple and breaks if rows are inserted. A cursor holds up for large listings/orders.",
         "Offset es simple y se rompe si insertan filas. Cursor aguanta listings/orders grandes."),
        ("Versioning", "Versionado",
         "URL /v2 vs a header. A breaking change is what eBay did without notice. Version or dual-run.",
         "URL /v2 vs header. Breaking change = lo que eBay hizo sin avisar. Versiona o dual-run."),
        ("eLink", "eLink",
         "One interface for listings/orders/inventory. Dual-run SOAP+REST. REST as the only writer once diffs were zero.",
         "Una interfaz listings/orders/inventory. Dual-run SOAP+REST. REST único writer con diffs en cero."),
    ]),
    ("w03-sql", "SQL", "SQL", ".NET services", "servicios .NET", [
        ("Joins", "Joins",
         "INNER: there is a match. LEFT: keep the left side. Three tables: do not fire N queries in a loop.",
         "INNER: hay match. LEFT: conserva la izquierda. Tres tablas: no hagas N queries en un loop."),
        ("Indexes", "Índices",
         "They speed up WHERE/JOIN. They cost writes and space. No index on an FK and the join scans.",
         "Aceleran WHERE/JOIN. Cuestan writes y espacio. Sin índice en FK, el join barre."),
        ("Normalization", "Normalización",
         "1NF–3NF: one fact, one place. You denormalize on purpose for reads, not out of laziness.",
         "1NF–3NF: un hecho, un lugar. Desnormalizas a propósito para leer, no por flojera."),
        ("Transactions", "Transacciones",
         "BEGIN/COMMIT. Isolation: the minimum is 'do not read dirty'. An order inserts completely or not at all.",
         "BEGIN/COMMIT. Isolation: lo mínimo es 'no leas sucio'. Un order se inserta entero o no."),
        ("N+1 and tuning", "N+1 y tuning",
         "N+1 = 1 query + N queries. EXPLAIN at a high level. Include/projection in EF is the same bug.",
         "N+1 = 1 query + N queries. EXPLAIN a alto nivel. Include/proyección en EF es el mismo bug."),
    ]),
    ("w04-git", "Git, PRs, CR", "Git, PRs, CR", "TFS → GitHub", "TFS → GitHub", [
        ("Branch and merge", "Branch y merge",
         "Short branch. Rebase vs merge: be able to say the tradeoff. Conflicts get resolved, not hidden.",
         "Branch corta. Rebase vs merge: sepas decir el tradeoff. Conflictos se resuelven, no se esconden."),
        ("Pull request", "Pull request",
         "What you ask for: behavior, tests, the cut. Not 40 formatting files.",
         "Qué pides: comportamiento, tests, el corte. No 40 archivos de format."),
        ("Code review", "Code review",
         "Bugs, names, tests, contract diffs. Not brace taste.",
         "Bugs, nombres, tests, el diff de contratos. No gustos de llaves."),
        ("Pipeline", "Pipeline",
         "Build → test → deploy. A comparable artifact. That is how they cut TFS.",
         "Build → test → deploy. Artefacto comparable. Así cortaron TFS."),
        ("The migration", "La migración",
         "TFVC → GitHub + YAML. Compare artifacts before turning TFS off. The hero is the cutover.",
         "TFVC → GitHub + YAML. Comparar artefactos antes de apagar TFS. El héroe es el corte."),
    ]),
    ("w05-azdo", "Azure DevOps", "Azure DevOps", "migration", "migración", [
        ("Map", "Mapa",
         "Boards, repos, pipelines. What lived in TFS and what moved to GitHub.",
         "Boards, repos, pipelines. Qué vivía en TFS y qué se fue a GitHub."),
        ("YAML pipeline", "YAML pipeline",
         "trigger, stage, job. The YAML is the build contract.",
         "trigger, stage, job. El YAML es el contrato del build."),
        ("Artifacts", "Artifacts",
         "The package you compare before cutover.",
         "El paquete que comparas antes del cutover."),
        ("Secrets", "Secrets",
         "Variables and service connections. Not in the repo.",
         "Variables y service connections. No en el repo."),
        ("What you did", "Lo que tú hiciste",
         "Vocabulary vs evidence: say the artifact diff, not the Azure menu.",
         "Vocabulario vs evidencia: di el diff de artefactos, no el menú de Azure."),
    ]),
    ("w06-tests", "Tests and mocks", "Tests y mock", "eLink", "eLink", [
        ("Unit vs integration", "Unit vs integration",
         "Unit: one unit, mocked deps. Integration: the real DB or HTTP.",
         "Unit: una unidad, deps mockeadas. Integration: la DB o el HTTP de verdad."),
        ("AAA", "AAA",
         "Arrange, Act, Assert. One strong assert beats ten weak ones.",
         "Arrange, Act, Assert. Un assert fuerte vale más que diez flojos."),
        ("What to mock", "Qué mockear",
         "I/O, the clock, the eBay client. Do not mock the system under test.",
         "I/O, reloj, el cliente eBay. No mockees el sistema bajo prueba."),
        ("xUnit / Moq", "xUnit / Moq",
         "Whatever you use in .NET. The library name is not the point.",
         "Lo que uses en .NET. El nombre de la lib no es el punto."),
        ("An eLink test", "Un test de eLink",
         "SOAP vs REST payload diff: that is a contract test.",
         "Diff de payload SOAP vs REST: eso es un test de contrato."),
    ]),
    ("w07-async-cs", "C# async", "C# async", ".NET APIs", "APIs .NET", [
        ("Task vs thread", "Task vs thread",
         "async is for I/O. It is not a new thread per request.",
         "async es para I/O. No es un thread nuevo por request."),
        ("await", "await",
         "It releases the thread while waiting on HTTP/SQL. The rest of the method continues after.",
         "Suelta el hilo mientras espera HTTP/SQL. El resto del método continúa después."),
        ("Deadlocks", "Deadlocks",
         ".Result / .Wait on classic ASP.NET = deadlock. await all the way.",
         ".Result / .Wait en ASP.NET clásico = deadlock. await todo el camino."),
        ("ConfigureAwait", "ConfigureAwait",
         "false in libraries. On modern ASP.NET Core it almost never bites. Say when.",
         "false en librerías. En ASP.NET Core moderno casi no muerde. Di cuándo."),
        ("Cancellation", "Cancelación",
         "CancellationToken on I/O. The client left: do not keep calling eBay.",
         "CancellationToken en I/O. El cliente se fue: no sigas el HTTP a eBay."),
    ]),
    ("w08-concurrency", "Concurrency", "Concurrencia", "APIs", "APIs", [
        ("Race and lock", "Race y lock",
         "Two requests stomp the same state. Lock or do not share.",
         "Dos requests pisan el mismo estado. Lock o no compartir."),
        ("Sync vs async I/O", "Sync vs async I/O",
         "Blocking the thread on HTTP is waste. You already saw this in async.",
         "Bloquear el hilo en HTTP es desperdicio. Ya lo viste en async."),
        ("Parallel vs concurrent", "Parallel vs concurrent",
         "Parallel uses several cores for CPU. Concurrent interleaves waits.",
         "Parallel usa varios cores en CPU. Concurrent entrelaza esperas."),
        ("Queue + worker", "Cola + worker",
         "You publish a message, another process works. Do not do it on the request.",
         "Publicas un mensaje, otro proceso trabaja. No lo hagas en el request."),
        ("State in an API", "Estado en un API",
         "A mutable singleton is a race. Scoped per request.",
         "Singleton mutable = carrera. Scoped por request."),
    ]),
    ("w09-linq", "LINQ", "LINQ", "Solera", "Solera", [
        ("Deferred", "Deferred",
         "Where does not run until you enumerate. ToList() materializes.",
         "Where no corre hasta que enumeras. ToList() materializa."),
        ("IEnumerable vs IQueryable", "IEnumerable vs IQueryable",
         "IQueryable goes to SQL. IEnumerable is in memory. That is where N+1 is born.",
         "IQueryable va a SQL. IEnumerable es en memoria. Ahí nace el N+1."),
        ("Operators", "Operadores",
         "Where, Select, GroupBy — only the ones you control.",
         "Where, Select, GroupBy — solo los que controlas."),
        ("LINQ and N+1", "LINQ y N+1",
         "A navigation foreach fires queries. Project or Include.",
         "Un foreach de navegación dispara queries. Proyecta o Include."),
        ("Now or later?", "¿Ahora o después?",
         "Five queries: say whether they run when defined or when enumerated.",
         "Cinco queries: di si se ejecutan al definirlas o al enumerar."),
    ]),
    ("w10-ef", "EF Core", "EF Core", "services", "servicios", [
        ("Migrations", "Migrations",
         "Versioned schema. Do not touch prod by hand.",
         "El schema versionado. No toques prod a mano."),
        ("Tracking", "Tracking",
         "The change tracker. AsNoTracking for reads.",
         "El change tracker. AsNoTracking para lecturas."),
        ("N+1", "N+1",
         "Include vs projection. Same idea as the join.",
         "Include vs proyección. Lo mismo que el join."),
        ("SaveChanges", "SaveChanges",
         "One transaction of tracked changes.",
         "Una transacción de cambios rastreados."),
        ("A query of yours", "Una query tuya",
         "Tracking yes or no, and why.",
         "Tracking sí o no, y por qué."),
    ]),
    ("w11-di-asp", "DI + ASP.NET", "DI + ASP.NET", "Solera", "Solera", [
        ("Transient / scoped / singleton", "Transient / scoped / singleton",
         "Per resolve, per request, one for the app. DbContext = scoped.",
         "Por resolución, por request, uno para la app. DbContext = scoped."),
        ("What you inject", "Qué inyectas",
         "The port (interface), not the concrete class if there is a test.",
         "El puerto (interfaz), no la clase concreta si hay test."),
        ("Middleware vs filters", "Middleware vs filtros",
         "Middleware = HTTP pipeline. Filters = MVC/endpoint.",
         "Middleware = pipeline HTTP. Filtros = MVC/endpoint."),
        ("Pipeline", "Pipeline",
         "Request in, response out. Draw four boxes.",
         "Request entra, sale la response. Dibuja 4 cajas."),
        ("Razor", "Razor",
         "Only if you touched it. If not, say so: do not recite classic MVC.",
         "Solo si lo tocaste. Si no, dilo: no recites MVC clásico."),
    ]),
    ("w12-solid", "SOLID + patterns", "SOLID + patterns", "your code", "tu código", [
        ("S and O", "S y O",
         "One reason to change. Extend without blowing up eLink.",
         "Una razón de cambio. Extiende sin reventar eLink."),
        ("L, I, D", "L, I, D",
         "One example or 'I do not have one'. Honesty beats a list.",
         "Un ejemplo o 'no lo tengo'. Honestidad > lista."),
        ("Repository / facade", "Repository / facade",
         "If it exists in your code. eLink's single interface is a facade.",
         "Si existe en tu código. La interfaz única de eLink es un facade."),
        ("Strategy / decorator", "Strategy / decorator",
         "Only with an anchor. Dual-run is a writer strategy.",
         "Solo con ancla. Dual-run es un strategy de writer."),
        ("Three names", "Tres nombres",
         "Name 3 you actually used. The rest is not recited.",
         "Nombra 3 que sí usaste. El resto no se recita."),
    ]),
    ("w13-scale", "Scale + logs", "Escala + logs", "eLink / SlabHQ", "eLink / SlabHQ", [
        ("Cache", "Cache",
         "What, where, invalidation. Cache without a TTL is a postponed bug.",
         "Qué, dónde, invalidación. Cache sin TTL es un bug aplazado."),
        ("Horizontal and LB", "Horizontal y LB",
         "More instances + balancing. Session on the server breaks.",
         "Más instancias + balanceo. Sesión en el server se rompe."),
        ("Queue / Rabbit", "Cola / Rabbit",
         "At-least-once: your handler must be idempotent (like REST).",
         "At-least-once: tu handler debe ser idempotente (como REST)."),
        ("Logs and traces", "Logs y traces",
         "How you find out. Dual-run = observability of diffs.",
         "Cómo te enteras. Dual-run = observabilidad de diffs."),
        ("A 500", "Un 500",
         "Log the request id, not 'check the server'.",
         "Log del request id, no 'revisa el server'."),
    ]),
    ("w14-gc-asyncio", "GC + asyncio", "GC + asyncio", "contrast", "contraste", [
        ("GC .NET", "GC .NET",
         "Gen 0/1/2. IDisposable for non-memory (sockets, files).",
         "Gen 0/1/2. IDisposable para no-memoria (sockets, files)."),
        ("What not to recite", "Qué no recitar",
         "Do not pretend you are a runtime engineer. High level is enough.",
         "No te hagas de runtime. Alto nivel basta."),
        ("Event loop", "Event loop",
         "Python async: one thread, one I/O queue.",
         "Python async: un hilo, una cola de I/O."),
        ("asyncio vs threads", "asyncio vs threads",
         "I/O → asyncio. CPU → processes. GIL in the middle.",
         "I/O → asyncio. CPU → procesos. GIL en el medio."),
        ("Contrast", "Contraste",
         "ConfigureAwait vs event loop: both mean 'do not block the I/O thread'.",
         "ConfigureAwait vs event loop: ambos 'no bloquees el hilo de I/O'."),
    ]),
    ("w15-gil-py", "GIL + Python shape", "GIL + forma Python", "Codenda", "Codenda", [
        ("GIL", "GIL",
         "One bytecode thread at a time. It exists because of CPython's memory model.",
         "Un hilo de bytecode a la vez. Existe por el memory model de CPython."),
        ("When which", "Cuándo qué",
         "threading: I/O. multiprocessing: CPU. asyncio: lots of I/O on one thread.",
         "threading: I/O. multiprocessing: CPU. asyncio: mucho I/O en un hilo."),
        ("Decorators and with", "Decoradores y with",
         "Decorator = a function that wraps. with = enter/exit.",
         "Decorador = función que envuelve. with = enter/exit."),
        ("Generators", "Generadores",
         "yield. One item at a time. Not the whole list.",
         "yield. Un item a la vez. No la lista entera."),
        ("Typing", "Typing",
         "def f(xs: list[int]) -> dict[int, int]. mypy in Codenda counts.",
         "def f(xs: list[int]) -> dict[int, int]. mypy en Codenda cuenta."),
    ]),
    ("w16-sa-pytest", "SQLAlchemy + pytest", "SQLAlchemy + pytest", "if the role is Python", "si la vacante es Python", [
        ("venv / poetry", "venv / poetry",
         "They isolate deps. The problem is 'works on my machine'.",
         "Aíslan deps. El problema es 'en mi máquina sí'."),
        ("SQLAlchemy vs EF", "SQLAlchemy vs EF",
         "Session ≈ DbContext. Query vs IQueryable.",
         "Session ≈ DbContext. Query vs IQueryable."),
        ("pytest fixtures", "pytest fixtures",
         "Reusable setup. Skip TestCase setUp if you can.",
         "Setup reutilizable. No setUp de TestCase si puedes evitarlo."),
        ("Python mocks", "mock Python",
         "unittest.mock. Same rule: mock I/O.",
         "unittest.mock. Igual: mockea I/O."),
        ("Python close", "Cierre Python",
         "What you say in a .NET interview: contrast. What you do not: a Flask course.",
         "Qué sí dices en entrevista .NET: contraste. Qué no: un curso Flask."),
    ]),
]


def _cards(sid: str, reading: str, reading_es: str, title: str, title_es: str, anchor: str, anchor_es: str) -> list[dict]:
    cards = []
    en_parts = [s.strip().rstrip(".") for s in reading.split(". ") if s.strip()]
    es_parts = [s.strip().rstrip(".") for s in reading_es.split(". ") if s.strip()]
    for n, (en, es) in enumerate(zip(en_parts, es_parts), start=1):
        cards.append({
            "id": f"{sid}-c{n}",
            "front": (en.split(",")[0][:80] + "?").replace("??", "?"),
            "front_es": (es.split(",")[0][:80] + "?").replace("??", "?"),
            "back": en + ".",
            "back_es": es + ".",
        })
    if len(cards) < 5:
        cards.append({
            "id": f"{sid}-cA",
            "front": f"Anchor for {title}?",
            "front_es": f"¿Ancla de {title_es}?",
            "back": f"{anchor}.",
            "back_es": f"{anchor_es}.",
        })
    return cards[:8]


def theory_weeks() -> list[dict]:
    sections: list[dict] = []
    idx = 0
    for week_id, week_en, week_es, anchor_en, anchor_es, days in WEEKS:
        for i, (title_en, title_es, reading_en, reading_es) in enumerate(days, start=1):
            idx += 1
            sid = f"{week_id}-s{i}"
            cards = _cards(sid, reading_en, reading_es, title_en, title_es, anchor_en, anchor_es)
            questions = [
                {
                    "id": f"{sid}-q1",
                    "q": f"In one sentence, what is {title_en}?",
                    "q_es": f"En una frase, ¿qué es {title_es}?",
                    "choices": [reading_en[:80], "Does not come up in interviews", "Certification theory only", "A GoF pattern"],
                    "choices_es": [reading_es[:80], "No aplica en entrevista", "Solo teoría de cert", "Un patrón GoF"],
                    "answer": 0,
                },
                {
                    "id": f"{sid}-q2",
                    "q": "Where did you use this / where will you say it?",
                    "q_es": "¿Dónde lo usaste / lo vas a decir?",
                    "choices": [anchor_en, "A YouTube tutorial", "The Azure cert", "I will not say it"],
                    "choices_es": [anchor_es, "Un tutorial de YouTube", "La cert de Azure", "No lo digo"],
                    "answer": 0,
                },
                {
                    "id": f"{sid}-q3",
                    "q": "If you have no anchor, what do you do?",
                    "q_es": "Si no hay ancla, ¿qué haces?",
                    "choices": ["It is not this week", "I memorize Wikipedia", "I skip it", "I ask for another cert"],
                    "choices_es": ["No es esta semana", "Memorizo Wikipedia", "Lo salto y ya", "Pido otra cert"],
                    "answer": 0,
                },
                {
                    "id": f"{sid}-q4",
                    "q": "What will you not recite?",
                    "q_es": "¿Qué no vas a recitar?",
                    "choices": ["The entire course list", reading_en[:60], anchor_en, "Two Sum Big O"],
                    "choices_es": ["La lista entera de un curso", reading_es[:60], anchor_es, "Big O de Two Sum"],
                    "answer": 0,
                },
            ]
            sections.append({
                "id": sid,
                "index": idx - 1,
                "week_id": week_id,
                "week_title": week_en,
                "week_title_es": week_es,
                "anchor": anchor_en,
                "anchor_es": anchor_es,
                "title": title_en,
                "title_es": title_es,
                "reading": reading_en,
                "reading_es": reading_es,
                "reading_en": reading_en,
                "questions": questions,
                "cards": cards,
                "standard_minutes": 35,
            })
    return sections
